import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  MonthlyAccountingSummary,
  MealRecord,
  Deposit,
  MessSettings,
} from '../types';
import { formatMonthLabel, formatDateShort, getTodayString } from '../utils/dateUtils';

export class PdfExportService {
  /**
   * Generates and downloads a clean, professional PDF Monthly Statement
   */
  static exportMonthlyReportPdf(
    summary: MonthlyAccountingSummary,
    _meals: MealRecord[],
    _deposits: Deposit[],
    settings: MessSettings
  ): void {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // Use ASCII-safe currency representation 'Tk' for standard PDF font compatibility
    // (Unicode '৳' converts to 'ó' in default PDF WinAnsi / Latin-1 encoding)
    const currencySymbol = 'Tk';
    const monthLabel = formatMonthLabel(summary.month);
    const totalDue = summary.totalDue ?? 0;
    const runningCost = summary.totalRunningMealCost ?? (summary.totalMeals * summary.mealRate);

    // 1. Header Banner
    doc.setFillColor(16, 185, 129); // emerald-600
    doc.rect(0, 0, 210, 26, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(settings.messName || 'Mess', 14, 15);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.text(`MONTHLY REPORT: ${monthLabel.toUpperCase()}`, 196, 11.5, { align: 'right' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.text('Generated by: Abidul Islam Safat', 196, 17.5, { align: 'right' });

    // 2. Executive Metrics Summary Box (4 metric cards)
    const startY = 31;
    const boxW = 43.5;
    const boxH = 19;
    const gap = 2.7;

    const metrics = [
      {
        title: 'TOTAL MEALS',
        value: `${summary.totalMeals}`,
        sub: `${summary.activeMemberCount} Active Members`,
        color: [240, 253, 244], // emerald-50
        border: [167, 243, 208],
        textCol: [6, 95, 70],
      },
      {
        title: 'MEAL RATE',
        value: `${currencySymbol} ${summary.mealRate.toFixed(2)}`,
        sub: 'Per Meal Cost',
        color: [239, 246, 255], // blue-50
        border: [191, 219, 254],
        textCol: [30, 64, 175],
      },
      {
        title: 'TOTAL DEPOSITS',
        value: `${currencySymbol} ${Math.round(summary.totalDeposits).toLocaleString('en-IN')}`,
        sub: 'Collected Funds',
        color: [240, 253, 250], // teal-50
        border: [153, 246, 228],
        textCol: [17, 94, 89],
      },
      {
        title: 'TOTAL DUE',
        value: totalDue > 0 ? `${currencySymbol} ${Math.round(totalDue).toLocaleString('en-IN')}` : `${currencySymbol} 0`,
        sub: totalDue > 0 ? 'Exceeds Deposits' : 'No Due (Covered)',
        color: totalDue > 0 ? [254, 242, 242] : [240, 253, 244],
        border: totalDue > 0 ? [254, 202, 202] : [167, 243, 208],
        textCol: totalDue > 0 ? [185, 28, 28] : [6, 95, 70],
      },
    ];

    metrics.forEach((m, idx) => {
      const x = 14 + idx * (boxW + gap);
      doc.setFillColor(m.color[0], m.color[1], m.color[2]);
      doc.setDrawColor(m.border[0], m.border[1], m.border[2]);
      doc.setLineWidth(0.3);
      doc.roundedRect(x, startY, boxW, boxH, 2, 2, 'FD');

      doc.setFontSize(6.8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 116, 139);
      doc.text(m.title, x + 3.5, startY + 5.2);

      doc.setFontSize(10.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(m.textCol[0], m.textCol[1], m.textCol[2]);
      doc.text(m.value, x + 3.5, startY + 11.8);

      doc.setFontSize(6.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      doc.text(m.sub, x + 3.5, startY + 16.2);
    });

    // 3. Sub-summary info bar
    const infoY = startY + boxH + 3.5;
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.2);
    doc.roundedRect(14, infoY, 182, 8, 1.5, 1.5, 'FD');

    doc.setFontSize(7.2);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const infoText = `Running Meal Cost: ${currencySymbol} ${Math.round(runningCost).toLocaleString('en-IN')}  |  Month: ${monthLabel}  |  Calculated: Total Meals (${summary.totalMeals}) x Meal Rate (${currencySymbol} ${summary.mealRate.toFixed(2)})`;
    doc.text(infoText, 17, infoY + 5.2);

    // 4. Member Breakdown Table
    const tableBody = summary.memberCalculations.map((calc, idx) => {
      const memberDue =
        calc.due !== undefined
          ? calc.due
          : calc.mealCost > calc.totalCredits
          ? calc.mealCost - calc.totalCredits
          : 0;
      const isPositive = calc.balance >= 0;
      const balanceText = isPositive
        ? `+${Math.round(calc.balance).toLocaleString('en-IN')} (Refund)`
        : `-${Math.round(Math.abs(calc.balance)).toLocaleString('en-IN')} (Due)`;

      return [
        idx + 1,
        calc.member.fullName + (calc.member.nickname ? ` (${calc.member.nickname})` : ''),
        calc.totalMeals,
        Math.round(calc.mealCost).toLocaleString('en-IN'),
        Math.round(calc.totalDeposits).toLocaleString('en-IN'),
        memberDue > 0 ? Math.round(memberDue).toLocaleString('en-IN') : '0',
        balanceText,
      ];
    });

    // Total Row
    const totalBalance = summary.memberCalculations.reduce((acc, m) => acc + m.balance, 0);
    const totalBalanceText =
      totalBalance >= 0
        ? `+${Math.round(totalBalance).toLocaleString('en-IN')}`
        : `-${Math.round(Math.abs(totalBalance)).toLocaleString('en-IN')}`;

    const totalRow = [
      '',
      `TOTAL (${summary.memberCalculations.length} Members)`,
      summary.totalMeals,
      Math.round(runningCost).toLocaleString('en-IN'),
      Math.round(summary.totalDeposits).toLocaleString('en-IN'),
      Math.round(totalDue).toLocaleString('en-IN'),
      totalBalanceText,
    ];

    autoTable(doc, {
      startY: infoY + 11,
      head: [
        [
          '#',
          'Member Name',
          'Meals',
          'Meal Cost (Tk)',
          'Deposit (Tk)',
          'Due (Tk)',
          'Balance (Tk)',
        ],
      ],
      body: [...tableBody, totalRow],
      theme: 'grid',
      headStyles: {
        fillColor: [16, 185, 129],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 7.8,
        halign: 'center',
        valign: 'middle',
      },
      styles: {
        font: 'helvetica',
        fontSize: 7.5,
        cellPadding: { top: 2, bottom: 2, left: 2, right: 2 },
        valign: 'middle',
      },
      columnStyles: {
        0: { halign: 'center', cellWidth: 8 },
        1: { halign: 'left', cellWidth: 46, fontStyle: 'bold' },
        2: { halign: 'center', cellWidth: 16 },
        3: { halign: 'right', cellWidth: 26, fontStyle: 'bold' },
        4: { halign: 'right', cellWidth: 26, textColor: [5, 150, 105], fontStyle: 'bold' },
        5: { halign: 'right', cellWidth: 24, fontStyle: 'bold' },
        6: { halign: 'right', cellWidth: 36, fontStyle: 'bold' },
      },
      didParseCell: (data) => {
        // Style individual Due column text
        if (data.column.index === 5 && data.row.index < tableBody.length) {
          const rawVal = data.cell.raw as string;
          if (rawVal && rawVal !== '0') {
            data.cell.styles.textColor = [225, 29, 72]; // rose-600
          } else {
            data.cell.styles.textColor = [148, 163, 184]; // slate-400
          }
        }

        // Style Balance column text (positive green, negative red)
        if (data.column.index === 6 && data.row.index < tableBody.length) {
          const rawVal = data.cell.raw as string;
          if (rawVal && rawVal.startsWith('+')) {
            data.cell.styles.textColor = [5, 150, 105]; // emerald-600
          } else if (rawVal && rawVal.startsWith('-')) {
            data.cell.styles.textColor = [225, 29, 72]; // rose-600
          }
        }

        // Style the last total row
        if (data.row.index === tableBody.length) {
          data.cell.styles.fillColor = [241, 245, 249];
          data.cell.styles.fontStyle = 'bold';
          data.cell.styles.textColor = [15, 23, 42];
        }
      },
      margin: { left: 14, right: 14 },
    });

    // Download trigger
    const cleanMonth = summary.month.replace(/[^a-zA-Z0-9_-]/g, '_');
    const fileName = `Monthly_Meal_Report_${cleanMonth}.pdf`;
    doc.save(fileName);
  }
}
